<?php


use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('program_list')->delete();

        $programs=[
            ['program_name' => 'BACHELOR OF BUSINESS INFORMATION SYSTEMS'],
            ['program_name' => 'BACHELOR OF COMMERCE (ACCOUNTING)'],
            ['program_name' => 'BACHELOR OF COMMERCE (ACCOUNTING AND FINANCE)'],
            ['program_name' => 'BACHELOR OF COMMERCE (COMMERCIAL LAW)'],
            ['program_name' => 'BACHELOR OF COMMERCE (ENTREPRENEURSHIP AND INNOVATION)'],
            ['program_name' => 'BACHELOR OF COMMERCE (FINANCE)'],
            ['program_name' => 'BACHELOR OF COMMERCE (HUMAN RESOURCE MANAGEMENT)'],
            ['program_name' => 'BACHELOR OF COMMERCE (INTERNATIONAL BUSINESS)'],
            ['program_name' => 'BACHELOR OF COMMERCE (MARKETING)'],
            ['program_name' => 'BACHELOR OF COMMERCE'],
            ['program_name' => 'MASTER OF MANAGEMENT'],
            ['program_name' => 'BACHELOR OF ENGINEERING (CIVIL ENGINEERING)'],
            ['program_name' => 'MASTER OF BUSINESS ADMINISTRATION (INTERNATIONAL)'],
            ['program_name' => 'MASTER OF COMMERCE BY RESEARCH'],
            ['program_name' => 'BACHELOR OF DESIGN (GRAPHIC DESIGN)'],
            ['program_name' => 'BACHELOR OF DESIGN (MULTIMEDIA DESIGN)'],
            ['program_name' => 'BACHELOR OF ENGINEERING (ELECTRICAL AND ELECTRONIC ENGINEERING)'],
            ['program_name' => 'BACHELOR OF ENGINEERING (CIVIL ENGINEERING)/ BACHELOR OF COMMERCE'],
            ['program_name' => 'MASTER OF ENGINEERING BY RESEARCH'],
            ['program_name' => 'BACHELOR OF ENGINEERING (MECHANICAL ENGINEERING)/ BACHELOR OF COMMERCE'],
            ['program_name' => 'BACHELOR OF ENGINEERING (ROBOTICS & MECHATRONICS) / BACHELOR OF SCIENCE (COMPUTER SCIENCE & SOFTWARE ENGINEERING)'],
            ['program_name' => 'BACHELOR OF ENGINEERING (ROBOTICS AND MECHATRONICS) / BACHELOR OF COMPUTER SCIENCE'],
            ['program_name' => 'BACHELOR OF INFORMATION AND COMMUNICATION TECHNOLOGY'],
            ['program_name' => 'BACHELOR OF COMPUTER SCIENCE'],
            ['program_name' => 'BACHELOR OF COMPUTING'],
            ['program_name' => 'BACHELOR OF ENGINEERING (TELECOMMUNICATION & NETWORK ENGINEERING)'],
            ['program_name' => 'BACHELOR OF BUSINESS INFORMATION SYSTEMS'],
            ['program_name' => 'MASTER OF SCIENCE BY RESEARCH'],
            ['program_name' => 'INTERNATIONAL EXCHANGE PROGRAM'],
            ['program_name' => 'INTERNATIONAL STUDY ABROAD PROGRAM (A)'],
            ['program_name' => 'INTERNATIONAL STUDY ABROAD PROGRAM (B)'],
            ['program_name' => 'INTERNATIONAL STUDY ABROAD PROGRAM (C)'],
            ['program_name' => 'INTERNATIONAL STUDY ABROAD PROGRAM (D)'],
            ['program_name' => 'INTERNATIONAL STUDY ABROAD PROGRAM (K)'],
            ['program_name' => 'SWINBURNE FOUNDATION STUDIES (BUSINESS)'],
            ['program_name' => 'SWINBURNE FOUNDATION STUDIES (DESIGN)'],
            ['program_name' => 'SWINBURNE FOUNDATION STUDIES (ENGINEERING/SCIENCE)'],
            ['program_name' => 'SWINBURNE FOUNDATION STUDIES (INFORMATION TECHNOLOGY/MULTIMEDIA)'],
            ['program_name' => 'BACHELOR OF ENGINEERING (MECHANICAL ENGINEERING)'],
            ['program_name' => 'BACHELOR OF ENGINEERING (ROBOTICS AND MECHATRONICS)'],
            ['program_name' => 'BACHELOR OF DESIGN (GRAPHIC DESIGN)'],
            ['program_name' => 'DOCTOR OF PHILOSOPHY (ENGINEERING)'],
            ['program_name' => 'DOCTOR OF PHILOSOPHY (SCIENCE)'],
            ['program_name' => 'DOCTOR OF PHILOSOPHY (BUSINESS)'],
            ['program_name' => 'INTENSIVE ENGLISH'],
            ['program_name' => 'DIPLOMA OF ENGINEERING'],
            ['program_name' => 'DIPLOMA OF BUSINESS AND INFORMATION SYSTEMS'],
            ['program_name' => 'DIPLOMA OF BUSINESS'],
            ['program_name' => 'BACHELOR OF ENGINEERING (HONOURS) IN CHEMICAL ENGINEERING'],
            ['program_name' => 'MASTER OF ARTS (TESOL)'],
            ['program_name' => 'SINGLE UNIT OF STUDY'],
            ['program_name' => 'BACHELOR OF SCIENCE (BIOTECHNOLOGY)'],
            ['program_name' => 'BACHELOR OF SCIENCE (COMPUTER SCIENCE AND SOFTWARE ENGINEERING)'],

        ];

		DB::table('program_list')->insert($programs);


DB::table('nationality_list')->delete();

        $nations=[
            ['nationality' => 'ANDORRAN'],
            ['nationality' => 'EMIRIAN'],
            ['nationality' => 'AFGHAN'],
            ['nationality' => 'ANTIGUAN'],
            ['nationality' => 'ANGUILLAN'],
            ['nationality' => 'ALBANIAN'],
            ['nationality' => 'ARMENIAN'],
            ['nationality' => 'ANTILLEAN'],
            ['nationality' => 'ANGOLAN'],
            ['nationality' => 'ARGENTINIAN'],
            ['nationality' => 'AMERICAN SAMOAN'],
            ['nationality' => 'AUSTRIAN'],
            ['nationality' => 'AUSTRALIAN'],
            ['nationality' => 'ARUBAN'],
            ['nationality' => 'AZERI'],
            ['nationality' => 'BOSNIAN'],
            ['nationality' => 'BARBADIAN'],
            ['nationality' => 'BANGLADESHI'],
            ['nationality' => 'BELGIAN'],
            ['nationality' => 'BURKINABE'],
            ['nationality' => 'BULGARIAN'],
            ['nationality' => 'BAHRAINI'],
            ['nationality' => 'BURUNDIAN'],
            ['nationality' => 'BENINESE'],
            ['nationality' => 'BERMUDIAN'],
            ['nationality' => 'BRUNEIAN'],
            ['nationality' => 'BOLIVIAN'],
            ['nationality' => 'BRAZILIAN'],
            ['nationality' => 'BAHAMIAN'],
            ['nationality' => 'BHUTANESE'],
            ['nationality' => 'BOTSWANAN'],
            ['nationality' => 'BELARUSIAN'],
            ['nationality' => 'BELIZEAN'],
            ['nationality' => 'CANADIAN'],
            ['nationality' => 'COCOS ISLANDER'],
            ['nationality' => 'CONGOLESE'],
            ['nationality' => 'CENTRAL AFRICAN'],
            ['nationality' => 'CONGOLESE'],
            ['nationality' => 'SWISS'],
            ['nationality' => 'IVORIAN'],
            ['nationality' => 'COOK ISLANDER'],
            ['nationality' => 'CHILEAN'],
            ['nationality' => 'CAMEROONIAN'],
            ['nationality' => 'CHINESE'],
            ['nationality' => 'COLOMBIAN'],
            ['nationality' => 'COSTA RICAN'],
            ['nationality' => 'SERBIA AND MONTENEGRO'],
            ['nationality' => 'CUBAN'],
            ['nationality' => 'CAPE VERDEAN'],
            ['nationality' => 'CHRISTMAS ISLANDER'],
            ['nationality' => 'CYPRIOT'],
            ['nationality' => 'CZECH'],
            ['nationality' => 'GERMAN'],
            ['nationality' => 'DJIBOUTIAN'],
            ['nationality' => 'DANISH'],
            ['nationality' => 'DOMINICAN'],
            ['nationality' => 'DOMINICAN'],
            ['nationality' => 'ALGERIAN'],
            ['nationality' => 'ECUADORIAN'],
            ['nationality' => 'ESTONIAN'],
            ['nationality' => 'EGYPTIAN'],
            ['nationality' => 'SAHRAWI'],
            ['nationality' => 'ERITREAN'],
            ['nationality' => 'SPANIARD'],
            ['nationality' => 'ETHIOPIAN'],
            ['nationality' => 'FINN'],
            ['nationality' => 'FIJIAN'],
            ['nationality' => 'FALKLAND ISLANDER'],
            ['nationality' => 'MICRONESIAN'],
            ['nationality' => 'FAEROESE'],
            ['nationality' => 'FRENCH'],
            ['nationality' => 'GABONESE'],
            ['nationality' => 'BRITON'],
            ['nationality' => 'GRENADIAN'],
            ['nationality' => 'GEORGIAN'],
            ['nationality' => 'GUIANESE'],
            ['nationality' => 'GHANAIAN'],
            ['nationality' => 'GIBRALTARIAN'],
            ['nationality' => 'GREENLANDER'],
            ['nationality' => 'GAMBIAN'],
            ['nationality' => 'GUINEAN'],
            ['nationality' => 'GUADELOUPEAN'],
            ['nationality' => 'EQUATORIAL GUINEAN'],
            ['nationality' => 'GREEK'],
            ['nationality' => 'GUATEMALAN'],
            ['nationality' => 'GUAMANIAN'],
            ['nationality' => 'GUINEA-BISSAU'],
            ['nationality' => 'GUYANESE'],
            ['nationality' => 'HONG KONG CHINESE'],
            ['nationality' => 'HONDURAN'],
            ['nationality' => 'CROAT'],
            ['nationality' => 'HAITIAN'],
            ['nationality' => 'HUNGARIAN'],
            ['nationality' => 'INDONESIAN'],
            ['nationality' => 'IRISH'],
            ['nationality' => 'ISRAELI'],
            ['nationality' => 'INDIAN'],
            ['nationality' => 'IRAQI'],
            ['nationality' => 'IRANIAN'],
            ['nationality' => 'ICELANDER'],
            ['nationality' => 'ITALIAN'],
            ['nationality' => 'JAMAICAN'],
            ['nationality' => 'JORDANIAN'],
            ['nationality' => 'JAPANESE'],
            ['nationality' => 'KENYAN'],
            ['nationality' => 'KYRGYZ'],
            ['nationality' => 'CAMBODIAN'],
            ['nationality' => 'KIRIBATIAN'],
            ['nationality' => 'COMORIAN'],
            ['nationality' => 'KITTSIAN'],
            ['nationality' => 'NORTH KOREAN'],
            ['nationality' => 'SOUTH KOREAN'],
            ['nationality' => 'KUWAITI'],
            ['nationality' => 'CAYMANIAN'],
            ['nationality' => 'KAZAKH'],
            ['nationality' => 'LAO'],
            ['nationality' => 'LEBANESE'],
            ['nationality' => 'SAINT LUCIAN'],
            ['nationality' => 'LIECHTENSTEINER'],
            ['nationality' => 'SRI LANKAN'],
            ['nationality' => 'LIBERIAN'],
            ['nationality' => 'BASOTHO'],
            ['nationality' => 'LITHUANIAN'],
            ['nationality' => 'LUXEMBOURGER'],
            ['nationality' => 'LATVIAN'],
            ['nationality' => 'LIBYAN'],
            ['nationality' => 'MOROCCAN'],
            ['nationality' => 'MONEGASQUE'],
            ['nationality' => 'MOLDOVAN'],
            ['nationality' => 'MALAGASY'],
            ['nationality' => 'MARSHALLESE'],
            ['nationality' => 'MACEDONIAN'],
            ['nationality' => 'MALIAN'],
            ['nationality' => 'BURMESE'],
            ['nationality' => 'MONGOLIAN'],
            ['nationality' => 'MACANESE'],
            ['nationality' => 'NORTHERN MARIANA ISLANDER'],
            ['nationality' => 'MARTINICAN'],
            ['nationality' => 'MAURITANIAN'],
            ['nationality' => 'MONTSERRATIAN'],
            ['nationality' => 'MALTESE'],
            ['nationality' => 'MAURITIAN'],
            ['nationality' => 'MALDIVIAN'],
            ['nationality' => 'MALAWIAN'],
            ['nationality' => 'MEXICAN'],
            ['nationality' => 'MALAYSIAN'],
            ['nationality' => 'MOZAMBICAN'],
            ['nationality' => 'NAMIBIAN'],
            ['nationality' => 'NEW CALEDONIAN'],
            ['nationality' => 'NIGERIEN'],
            ['nationality' => 'NORFOLK ISLANDER'],
            ['nationality' => 'NIGERIAN'],
            ['nationality' => 'NICARAGUAN'],
            ['nationality' => 'DUTCH'],
            ['nationality' => 'NORWEGIAN'],
            ['nationality' => 'NEPALESE'],
            ['nationality' => 'NAURUAN'],
            ['nationality' => 'NIUEAN'],
            ['nationality' => 'NEW ZEALANDER'],
            ['nationality' => 'OMANI'],
            ['nationality' => 'PANAMANIAN'],
            ['nationality' => 'PERUVIAN'],
            ['nationality' => 'POLYNESIAN'],
            ['nationality' => 'PAPUA NEW GUINEAN'],
            ['nationality' => 'FILIPINO'],
            ['nationality' => 'PAKISTANI'],
            ['nationality' => 'POLE'],
            ['nationality' => 'SAINT-PIERRAIS'],
            ['nationality' => 'PITCAIRNER'],
            ['nationality' => 'PUERTO RICAN'],
            ['nationality' => 'PALESTINE'],
            ['nationality' => 'PORTUGUESE'],
            ['nationality' => 'PALAUAN'],
            ['nationality' => 'PARAGUAYAN'],
            ['nationality' => 'QATARI'],
            ['nationality' => 'REUNIONESE'],
            ['nationality' => 'ROMANIAN'],
            ['nationality' => 'RUSSIAN'],
            ['nationality' => 'RWANDAN'],
            ['nationality' => 'SAUDI ARABIAN'],
            ['nationality' => 'SOLOMON ISLANDER'],
            ['nationality' => 'SEYCHELLOIS'],
            ['nationality' => 'SUDANESE'],
            ['nationality' => 'SWEDE'],
            ['nationality' => 'SINGAPOREAN'],
            ['nationality' => 'SAINT HELENIAN'],
            ['nationality' => 'SLOVENE'],
           

        ];

        DB::table('nationality_list')->insert($nations);




DB::table('religion_list')->delete();

        $religions=[
            ['religion' => 'BUDDHIST'],
            ['religion' => 'CHRISTIAN'],
            ['religion' => 'HINDU'],
            ['religion' => 'MUSLIM'],
            ['religion' => 'OTHERS'],
            ['religion' => 'TAOISM'],
        ];

        DB::table('religion_list')->insert($religions);



DB::table('booking_fee')->delete();

        $fee=[
            ['amount' => 0],
            ['amount' => 500],

        ];

        DB::table('booking_fee')->insert($fee);



DB::table('booking_confirm')->delete();

        $confirm=[
            ['confirmation' => 'Confirmed'],
            ['confirmation' => 'Tentative'],

        ];

        DB::table('booking_confirm')->insert($confirm);



DB::table('option_detail')->delete();

        $option_choice=[
            ['option' => 'A', 'weekly_rate'=> 95, 'deposite'=>380],
            ['option' => 'B', 'weekly_rate'=> 155, 'deposite'=>620],
            ['option' => 'C', 'weekly_rate'=> 152.5, 'deposite'=>610],
            ['option' => 'D', 'weekly_rate'=> 232.5, 'deposite'=>930],

        ];

        DB::table('option_detail')->insert($option_choice);




DB::table('country_list')->delete();

        $country=[

            ['country_name' => 'AD- ANDORRA'],
            ['country_name' => 'AE- UNITED ARAB EMIRATES'],
            ['country_name' => 'AF- AFGHANISTAN'],
            ['country_name' => 'AG- ANTIGUA AND BARBUDA'],
            ['country_name' => 'AI- ANGUILLA'],
            ['country_name' => 'AL- ALBANIA'],
            ['country_name' => 'AM- ARMENIA'],
            ['country_name' => 'AN- NETHERLANDS ANTILLES'],
            ['country_name' => 'AO- ANGOLA'],
            ['country_name' => 'AR- ARGENTINA'],
            ['country_name' => 'AS- AMERICAN SAMOA'],
            ['country_name' => 'AT- AUSTRIA'],
            ['country_name' => 'AU- AUSTRALIA'],
            ['country_name' => 'AW- ARUBA'],
            ['country_name' => 'AZ- AZERBAIJAN'],
            ['country_name' => 'BA- BOSNIA AND HERZEGOVINA17'],
            ['country_name' => 'BB- BARBADOS'],
            ['country_name' => 'BD- BANGLADESH'],
            ['country_name' => 'BE- BELGIUM'],
            ['country_name' => 'BF- BURKINA FASO'],
            ['country_name' => 'BG- BULGARIA'],
            ['country_name' => 'BH- BAHRAIN'],
            ['country_name' => 'BI- BURUNDI'],
            ['country_name' => 'BJ- BENIN'],
            ['country_name' => 'BM- BERMUDA'],
            ['country_name' => 'BN- BRUNEI DARUSSALAM'],
            ['country_name' => 'BO- BOLIVIA'],
            ['country_name' => 'BR- BRAZIL'],
            ['country_name' => 'BS- THE BAHAMAS'],
            ['country_name' => 'BT- BHUTAN'],
            ['country_name' => 'BW- BOTSWANA'],
            ['country_name' => 'BY- BELARUS'],
            ['country_name' => 'BZ- BELIZE'],
            ['country_name' => 'CA- CANADA'],
            ['country_name' => 'CC- COCOS (KEELING) ISLANDS'],
            ['country_name' => 'CD- DEMOCRATIC REPUBLIC OF THE CONGO32'],
            ['country_name' => 'CF- CENTRAL AFRICAN REPUBLIC'],
            ['country_name' => 'CG- CONGO27'],
            ['country_name' => 'CH- SWITZERLAND'],
            ['country_name' => 'CI- C?TE DIVOIRE'],
            ['country_name' => 'CK- COOK ISLANDS'],
            ['country_name' => 'CL- CHILE'],
            ['country_name' => 'CM- CAMEROON'],
            ['country_name' => "CN- PEOPLE'S REPUBLIC OF CHINA"],
            ['country_name' => 'CO- COLOMBIA'],
            ['country_name' => 'CR- COSTA RICA'],
            ['country_name' => 'CS- SERBIA AND MONTENEGRO'],
            ['country_name' => 'CU- CUBA'],
            ['country_name' => 'CV- CAPE VERDE'],
            ['country_name' => 'CX- CHRISTMAS ISLAND'],
            ['country_name' => 'CY- CYPRUS'],
            ['country_name' => 'CZ- CZECH REPUBLIC'],
            ['country_name' => 'DE- GERMANY'],
            ['country_name' => 'DJ- DJIBOUTI'],
            ['country_name' => 'DK- DENMARK'],
            ['country_name' => 'DM- DOMINICA'],
            ['country_name' => 'DO- DOMINICAN REPUBLIC'],
            ['country_name' => 'DZ- ALGERIA'],
            ['country_name' => 'EC- ECUADOR'],
            ['country_name' => 'EE- ESTONIA'],
            ['country_name' => 'EG- EGYPT'],
            ['country_name' => 'EH- WESTERN SAHARA85'],
            ['country_name' => 'ER- ERITREA'],
            ['country_name' => 'ES- SPAIN'],
            ['country_name' => 'ET- ETHIOPIA'],
            ['country_name' => 'FI- FINLAND'],
            ['country_name' => 'FJ- FIJI'],
            ['country_name' => 'FK- FALKLAND ISLANDS'],
            ['country_name' => 'FM- MICRONESIA'],
            ['country_name' => 'FO- FAEROE ISLANDS'],
            ['country_name' => 'FR- FRANCE'],
            ['country_name' => 'GA- GABON'],
            ['country_name' => 'GB- UNITED KINGDOM'],
            ['country_name' => 'GD- GRENADA'],
            ['country_name' => 'GE- GEORGIA'],
            ['country_name' => 'GF- FRENCH GUIANA'],
            ['country_name' => 'GH- GHANA'],
            ['country_name' => 'GI- GIBRALTAR'],
            ['country_name' => 'GL- GREENLAND'],
            ['country_name' => 'GM- THE GAMBIA'],
            ['country_name' => 'GN- GUINEA'],
            ['country_name' => 'GP- GUADELOUPE'],
            ['country_name' => 'GQ- EQUATORIAL GUINEA'],
            ['country_name' => 'GR- GREECE'],
            ['country_name' => 'GT- GUATEMALA'],
            ['country_name' => 'GU- GUAM'],
            ['country_name' => 'GW- GUINEA-BISSAU'],
            ['country_name' => 'GY- GUYANA'],
            ['country_name' => 'HK- HONG KONG'],
            ['country_name' => 'HN- HONDURAS'],
            ['country_name' => 'HR- CROATIA'],
            ['country_name' => 'HT- HAITI'],
            ['country_name' => 'HU- HUNGARY'],
            ['country_name' => 'ID- INDONESIA'],
            ['country_name' => 'IE- IRELAND'],
            ['country_name' => 'IL- ISRAEL'],
            ['country_name' => 'IN- INDIA'],
            ['country_name' => 'IQ- IRAQ'],
            ['country_name' => 'IR- IRAN'],
            ['country_name' => 'IS- ICELAND'],
            ['country_name' => 'IT- ITALY'],
            ['country_name' => 'JM- JAMAICA'],
            ['country_name' => 'JO- JORDAN'],
            ['country_name' => 'JP- JAPAN'],
            ['country_name' => 'KE- KENYA'],
            ['country_name' => 'KG- KYRGYZSTAN'],
            ['country_name' => 'KH- CAMBODIA'],
            ['country_name' => 'KI- KIRIBATI45'],
            ['country_name' => 'KM- COMOROS'],
            ['country_name' => 'KN- SAINT KITTS AND NEVIS'],
            ['country_name' => 'KP- NORTH KOREA'],
            ['country_name' => 'KR- SOUTH KOREA'],
            ['country_name' => 'KW- KUWAIT'],
            ['country_name' => 'KY- CAYMAN ISLANDS'],
            ['country_name' => 'KZ- KAZAKHSTAN'],
            ['country_name' => 'LA- LAOS'],
            ['country_name' => 'LB- LEBANON'],
            ['country_name' => 'LC- SAINT LUCIA'],
            ['country_name' => 'LI- LIECHTENSTEIN'],
            ['country_name' => 'LK- SRI LANKA'],
            ['country_name' => 'LR- LIBERIA'],
            ['country_name' => 'LS- LESOTHO'],
            ['country_name' => 'LT- LITHUANIA'],
            ['country_name' => 'LU- LUXEMBOURG'],
            ['country_name' => 'LV- LATVIA'],
            ['country_name' => 'LY- LIBYA'],
            ['country_name' => 'MA- MOROCCO'],
            ['country_name' => 'MC- MONACO'],
            ['country_name' => 'MD- MOLDOVA'],
            ['country_name' => 'MG- MADAGASCAR'],
            ['country_name' => 'MH- MARSHALL ISLANDS'],
            ['country_name' => 'MK- FORMER YUGOSLAV REPUBLIC OF MACEDONIA'],
            ['country_name' => 'ML- MALI'],
            ['country_name' => 'MM- MYANMAR'],
            ['country_name' => 'MN- MONGOLIA'],
            ['country_name' => 'MO- MACAU'],
            ['country_name' => 'MP- NORTHERN MARIANAS'],
            ['country_name' => 'MQ- MARTINIQUE'],
            ['country_name' => 'MR- MAURITANIA'],
            ['country_name' => 'MS- MONTSERRAT'],
            ['country_name' => 'MT- MALTA'],
            ['country_name' => 'MU- MAURITIUS'],
            ['country_name' => 'MV- MALDIVES'],
            ['country_name' => 'MW- MALAWI'],
            ['country_name' => 'MX- MEXICO'],
            ['country_name' => 'MY- MALAYSIA'],
            ['country_name' => 'MZ- MOZAMBIQUE'],
            ['country_name' => 'NA- NAMIBIA'],
            ['country_name' => 'NC- NEW CALEDONIA'],
            ['country_name' => 'NE- NIGER'],
            ['country_name' => 'NF- NORFOLK ISLAND'],
            ['country_name' => 'NG- NIGERIA'],
            ['country_name' => 'NI- NICARAGUA'],
            ['country_name' => 'NL- NETHERLANDS'],
            ['country_name' => 'NO- NORWAY'],
            ['country_name' => 'NP- NEPAL'],
            ['country_name' => 'NR- NAURU'],
            ['country_name' => 'NU- NIUE'],
            ['country_name' => 'NZ- NEW ZEALAND'],
            ['country_name' => 'OM- OMAN'],
            ['country_name' => 'PA- PANAMA'],
            ['country_name' => 'PE- PERU'],
            ['country_name' => 'PF- FRENCH POLYNESIA'],
            ['country_name' => 'PG- PAPUA NEW GUINEA'],
            ['country_name' => 'PH- PHILIPPINES'],
            ['country_name' => 'PK- PAKISTAN'],
            ['country_name' => 'PL- POLAND'],
            ['country_name' => 'PM- SAINT PIERRE AND MIQUELON'],
            ['country_name' => 'PN- PITCAIRN ISLANDS'],
            ['country_name' => 'PR- PUERTO RICO'],
            ['country_name' => 'PS- PALESTINE'],
            ['country_name' => 'PT- PORTUGAL'],
            ['country_name' => 'PW- PALAU'],
            ['country_name' => 'PY- PARAGUAY'],
            ['country_name' => 'QA- QATAR'],
            ['country_name' => 'RE- R?UNION'],
            ['country_name' => 'RO- ROMANIA'],
            ['country_name' => 'RU- RUSSIA'],
            ['country_name' => 'RW- RWANDA'],
            ['country_name' => 'SA- SAUDI ARABIA'],
            ['country_name' => 'SB- SOLOMON ISLANDS'],
            ['country_name' => 'SC- SEYCHELLES'],
            ['country_name' => 'SD- SUDAN'],
            ['country_name' => 'SE- SWEDEN'],
            ['country_name' => 'SG- SINGAPORE'],
            ['country_name' => 'SH- SAINT HELENA'],
            ['country_name' => 'SI- SLOVENIA'],
            ['country_name' => 'SK- SLOVAKIA'],
            ['country_name' => 'SL- SIERRA LEONE'],
            ['country_name' => 'SM- SAN MARINO'],
            ['country_name' => 'SN- SENEGAL'],
            ['country_name' => 'SO- SOMALIA'],
            ['country_name' => 'SR- SURINAME'],
            ['country_name' => 'SS- SOUTH SUDAN'],
            ['country_name' => 'ST- S?O TOM? AND PR?NCIPE'],
            ['country_name' => 'SV- EL SALVADOR'],
            ['country_name' => 'SY- SYRIA'],
            ['country_name' => 'SZ- SWAZILAND'],
            ['country_name' => 'TC- TURKS AND CAICOS ISLANDS'],
            ['country_name' => 'TD- CHAD'],
            ['country_name' => 'TG- TOGO'],
            ['country_name' => 'TH- THAILAND'],
            ['country_name' => 'TJ- TAJIKISTAN'],
            ['country_name' => 'TK- TOKELAU'],
            ['country_name' => 'TL- TIMOR-LESTE'],
            ['country_name' => 'TM- TURKMENISTAN'],
            ['country_name' => 'TN- TUNISIA'],
            ['country_name' => 'TO- TONGA'],
            ['country_name' => 'TR- TURKEY'],
            ['country_name' => 'TT- TRINIDAD AND TOBAGO'],
            ['country_name' => 'TV- TUVALU'],
            ['country_name' => 'TW- TAIWAN'],
            ['country_name' => 'TZ- TANZANIA'],
            ['country_name' => 'UA- UKRAINE'],
            ['country_name' => 'UG- UGANDA'],
            ['country_name' => 'US- UNITED STATES OF AMERICA'],
            ['country_name' => 'UY- URUGUAY'],
            ['country_name' => 'UZ- UZBEKISTAN'],
            ['country_name' => 'VC- SAINT VINCENT AND THE GRENADINES'],
            ['country_name' => 'VE- VENEZUELA'],
            ['country_name' => 'VG- BRITISH VIRGIN ISLANDS'],
            ['country_name' => 'VI- US VIRGIN ISLANDS'],
            ['country_name' => 'VN- VIETNAM'],
            ['country_name' => 'VU- VANUATU'],
            ['country_name' => 'WF- WALLIS AND FUTUNA'],
            ['country_name' => 'WS- SAMOA'],
            ['country_name' => 'YE- YEMEN'],
            ['country_name' => 'YT- MAYOTTE'],
            ['country_name' => 'ZA- SOUTH AFRICA'],
            ['country_name' => 'ZM- ZAMBIA'],
            ['country_name' => 'ZW- ZIMBABWE'],

];

        DB::table('country_list')->insert($country);


DB::table('tenancy_of_hostel')->delete();

        $tenancy=[
            ['tenancy_type' => 'New'],
            ['tenancy_type' => 'Continuing'],

        ];

        DB::table('tenancy_of_hostel')->insert($tenancy);


DB::table('sponsorship_list')->delete();

        $sponsor=[

            ['sponsorship_name' => 'NIL'],
            ['sponsorship_name' => 'Yayasan Sarawak BESTARI Scholarship'],
            ['sponsorship_name' => 'Sarawakian Bumiputera Financial Scheme'],
            ['sponsorship_name' => 'Sarawakian Diploma Bursary Scheme'],
            ['sponsorship_name' => 'Yayasan Sarawak (Student Project Scheme)'],
            ['sponsorship_name' => 'Yayasan Peneraju Pendidikan Bumiputera'],
            ['sponsorship_name' => 'Yayasan Sarawak Scholarship Loan (PoliSUTS Project)'],
            ['sponsorship_name' => 'Yayasan Sarawak Scholarship Loan (UiTM Project)'],
            ['sponsorship_name' => 'MARA'],
            ['sponsorship_name' => 'JPA'],
            ['sponsorship_name' => 'PTPTN'],
            ['sponsorship_name' => 'THERS'],

        ];

        DB::table('sponsorship_list')->insert($sponsor);



DB::table('room_occupancy')->delete();

        $occupancy=[
            ['occupancy_status' => 'Occupied'],
            ['occupancy_status' => 'Vacant'],

        ];

        DB::table('room_occupancy')->insert($occupancy);



DB::table('program_detail')->delete();

        $detail=[
            ['postgraduate_program' => 'MBA', 'teaching_start' => Carbon::create('2016', '2', '1'), 
                                                'teaching_end' => Carbon::create('2016', '3', '21'), 
                                                  'exam_start' => Carbon::create('2016', '3', '28'), 
                                                    'exam_end' => Carbon::create('2016', '4', '8'), 
                                                   'shortcode' => '(MBA)-Term 1'],

            ['postgraduate_program' => 'MBA', 'teaching_start' => Carbon::create('2016', '4', '25'), 
                                                'teaching_end' => Carbon::create('2016', '6', '13'), 
                                                  'exam_start' => Carbon::create('2016', '6', '20'), 
                                                    'exam_end' => Carbon::create('2016', '7', '1'), 
                                                   'shortcode' => '(MBA)-Term 2'],

            ['postgraduate_program' => 'MBA', 'teaching_start' => Carbon::create('2016', '7', '18'), 
                                                'teaching_end' => Carbon::create('2016', '9', '5'), 
                                                  'exam_start' => Carbon::create('2016', '9', '12'), 
                                                    'exam_end' => Carbon::create('2016', '9', '23'), 
                                                   'shortcode' => '(MBA)-Term 3'],         

            ['postgraduate_program' => 'MBA', 'teaching_start' => Carbon::create('2016', '10', '16'), 
                                                'teaching_end' => Carbon::create('2016', '11', '28'), 
                                                  'exam_start' => Carbon::create('2016', '12', '5'), 
                                                    'exam_end' => Carbon::create('2016', '12', '16'), 
                                                   'shortcode' => '(MBA)-Term 4'],          
 
            ['postgraduate_program' => 'MA (TESOL)', 'teaching_start' => Carbon::create('2016', '2', '29'), 
                                                'teaching_end' => Carbon::create('2016', '5', '30'), 
                                                  'exam_start' => Carbon::create('2016', '6', '6'), 
                                                    'exam_end' => Carbon::create('2016', '6', '10'), 
                                                   'shortcode' => '(MA TESOL)-Sem 1'], 

            ['postgraduate_program' => 'MA (TESOL)', 'teaching_start' => Carbon::create('2016', '8', '22'), 
                                                'teaching_end' => Carbon::create('2016', '11', '14'), 
                                                  'exam_start' => Carbon::create('2016', '11', '21'), 
                                                    'exam_end' => Carbon::create('2016', '11', '25'), 
                                                   'shortcode' => '(MA TESOL)-Sem 2'], 

            ['postgraduate_program' => 'Bachelor Degree - Summer Semester', 'teaching_start' => Carbon::create('2016', '1', '11'), 
                                                'teaching_end' => Carbon::create('2016', '2', '15'), 
                                                  'exam_start' => Carbon::create('2016', '2', '22'), 
                                                    'exam_end' => Carbon::create('2016', '2', '26'), 
                                                   'shortcode' => '(Deg)-Summer'], 

            ['postgraduate_program' => 'Bachelor Degree - Semester 1', 'teaching_start' => Carbon::create('2016', '2', '29'), 
                                                'teaching_end' => Carbon::create('2016', '5', '23'), 
                                                  'exam_start' => Carbon::create('2016', '5', '30'), 
                                                    'exam_end' => Carbon::create('2016', '6', '17'), 
                                                   'shortcode' => '(Deg)-Sem 1 (New&Cont.)'], 

            ['postgraduate_program' => 'Bachelor Degree - Semester 1', 'teaching_start' => Carbon::create('2016', '3', '7'), 
                                                'teaching_end' => Carbon::create('2016', '5', '23'), 
                                                  'exam_start' => Carbon::create('2016', '5', '30'), 
                                                    'exam_end' => Carbon::create('2016', '6', '17'), 
                                                   'shortcode' => '(Deg)-Sem 1 (If taking Summer Semester)'], 

            ['postgraduate_program' => 'Bachelor Degree - Winter', 'teaching_start' => Carbon::create('2016', '6', '20'), 
                                                'teaching_end' => Carbon::create('2016', '7', '25'), 
                                                  'exam_start' => Carbon::create('2016', '8', '1'), 
                                                    'exam_end' => Carbon::create('2016', '8', '5'), 
                                                   'shortcode' => '(Deg)-Winter-(New)'], 

            ['postgraduate_program' => 'Bachelor Degree - Winter', 
                                              'teaching_start' => Carbon::create('2016', '6', '27'), 
                                                'teaching_end' => Carbon::create('2016', '7', '25'), 
                                                  'exam_start' => Carbon::create('2016', '8', '1'), 
                                                    'exam_end' => Carbon::create('2016', '8', '5'), 
                                                   'shortcode' => '(Deg)-Winter (Cont. from Sem 1) '], 

            ['postgraduate_program' => 'Bachelor Degree - Semester 2', 
                                              'teaching_start' => Carbon::create('2016', '8', '22'), 
                                                'teaching_end' => Carbon::create('2016', '11', '14'), 
                                                  'exam_start' => Carbon::create('2016', '11', '21'), 
                                                    'exam_end' => Carbon::create('2016', '11', '9'), 
                                                   'shortcode' => '(Deg)-Sem 2 (New&Cont.)'], 

            ['postgraduate_program' => 'Bachelor Degree (A Level) - Sem 1', 
                                              'teaching_start' => Carbon::create('2016', '8', '17'), 
                                                'teaching_end' => Carbon::create('2016', '1', '16'), 
                                                  'exam_start' => Carbon::create('2016', '1', '23'), 
                                                    'exam_end' => Carbon::create('2016', '1', '27'), 
                                                   'shortcode' => '(Deg)-Sem 1 (A Level)-New'], 

            ['postgraduate_program' => 'Foundation - Summer Semester', 
                                              'teaching_start' => Carbon::create('2016', '1', '11'), 
                                                'teaching_end' => Carbon::create('2016', '2', '15'), 
                                                  'exam_start' => Carbon::create('2016', '2', '22'), 
                                                    'exam_end' => Carbon::create('2016', '2', '26'), 
                                                   'shortcode' => '(FND)-Summer'], 

             ['postgraduate_program' => 'Foundation - Semester 1', 
                                              'teaching_start' => Carbon::create('2016', '3', '28'), 
                                                'teaching_end' => Carbon::create('2016', '6', '27'), 
                                                  'exam_start' => Carbon::create('2016', '7', '4'), 
                                                    'exam_end' => Carbon::create('2016', '7', '8'), 
                                                   'shortcode' => '(FND)-Sem 1 (New&Cont.)'], 

            ['postgraduate_program' => 'Foundation - Winter Semester', 
                                              'teaching_start' => Carbon::create('2016', '7', '11'), 
                                                'teaching_end' => Carbon::create('2016', '8', '15'), 
                                                  'exam_start' => Carbon::create('2016', '8', '22'), 
                                                    'exam_end' => Carbon::create('2016', '8', '26'), 
                                                   'shortcode' => '(FND)-Winter (New)'], 

            ['postgraduate_program' => 'Foundation - Winter Semester', 
                                              'teaching_start' => Carbon::create('2016', '7', '18'), 
                                                'teaching_end' => Carbon::create('2016', '8', '15'), 
                                                  'exam_start' => Carbon::create('2016', '8', '22'), 
                                                    'exam_end' => Carbon::create('2016', '8', '26'), 
                                                   'shortcode' => '(FND)-Winter (Cont. from Sem 1)'], 
      
            ['postgraduate_program' => 'Foundation - Semester 2', 
                                              'teaching_start' => Carbon::create('2016', '9', '12'), 
                                                'teaching_end' => Carbon::create('2016', '12', '12'), 
                                                  'exam_start' => Carbon::create('2016', '12', '19'), 
                                                    'exam_end' => Carbon::create('2016', '12', '23'), 
                                                   'shortcode' => '(FND)-Sem 2 (New&Cont.)'], 
      
            ['postgraduate_program' => 'Intensive English - Semester 1', 
                                              'teaching_start' => Carbon::create('2016', '4', '4'), 
                                                'teaching_end' => Carbon::create('2016', '5', '30'), 
                                                  'exam_start' => Carbon::create('2016', '6', '6'), 
                                                    'exam_end' => Carbon::create('2016', '6', '10'), 
                                                   'shortcode' => '(IE)-Sem 1'], 
      
            ['postgraduate_program' => 'Intensive English - Semester 2', 
                                              'teaching_start' => Carbon::create('2016', '6', '20'), 
                                                'teaching_end' => Carbon::create('2016', '8', '15'), 
                                                  'exam_start' => Carbon::create('2016', '8', '22'), 
                                                    'exam_end' => Carbon::create('2016', '8', '26'), 
                                                   'shortcode' => '(IE)-Sem 2'], 

            ['postgraduate_program' => 'Intensive English - Semester 3', 
                                              'teaching_start' => Carbon::create('2016', '9', '19'), 
                                                'teaching_end' => Carbon::create('2016', '11', '14'), 
                                                  'exam_start' => Carbon::create('2016', '11', '21'), 
                                                    'exam_end' => Carbon::create('2016', '11', '25'), 
                                                   'shortcode' => '(IE)-Sem 3'], 
      
            ['postgraduate_program' => 'Intensive English - Semester 4', 
                                              'teaching_start' => Carbon::create('2016', '11', '28'), 
                                                'teaching_end' => Carbon::create('2017', '2', '6'), 
                                                  'exam_start' => Carbon::create('2017', '2', '13'), 
                                                    'exam_end' => Carbon::create('2017', '2', '17'), 
                                                   'shortcode' => '(IE)-Sem 4'], 
                    
            ['postgraduate_program' => 'Intensive English - Semester 4', 
                                              'teaching_start' => Carbon::create('2016', '12', '5'), 
                                                'teaching_end' => Carbon::create('2017', '2', '6'), 
                                                  'exam_start' => Carbon::create('2017', '2', '13'), 
                                                    'exam_end' => Carbon::create('2017', '2', '17'), 
                                                   'shortcode' => '(IE) - Sem 4 (Cont.)'], 

            ['postgraduate_program' => 'ISAP Korea - Semester 1', 
                                              'teaching_start' => Carbon::create('2016', '3', '7'), 
                                                'teaching_end' => Carbon::create('2016', '5', '30'), 
                                                  'exam_start' => Carbon::create('2016', '6', '6'), 
                                                    'exam_end' => Carbon::create('2016', '6', '10'), 
                                                   'shortcode' => '(ISAP Korea)-Sem 1'], 
      
            ['postgraduate_program' => 'ISAP Korea - Semester 2', 
                                              'teaching_start' => Carbon::create('2016', '9', '19'), 
                                                'teaching_end' => Carbon::create('2017', '12', '16'), 
                                                  'exam_start' => Carbon::create('2017', '12', '19'), 
                                                    'exam_end' => Carbon::create('2017', '12', '23'), 
                                                   'shortcode' => '(ISAP Korea) - Sem 2'], 
                    
                                    
        ];

        DB::table('program_detail')->insert($detail);



DB::table('room_status')->delete();

        $status=[
            ['room_no' => 'HM001', 'option_choice'=>'C'],
            ['room_no' => 'HM002', 'option_choice'=>'C'],
            ['room_no' => 'HM003', 'option_choice'=>'C'],
            ['room_no' => 'HM004', 'option_choice'=>'C'],      
            ['room_no' => 'HM005', 'option_choice'=>'D'],
            ['room_no' => 'HM006', 'option_choice'=>'C'],
            ['room_no' => 'HM007', 'option_choice'=>'d'],
            ['room_no' => 'HM008', 'option_choice'=>'C'],
            ['room_no' => 'HM009', 'option_choice'=>'D'],
            ['room_no' => 'HM010', 'option_choice'=>'D'],
            ['room_no' => 'HM011', 'option_choice'=>'C'],
            ['room_no' => 'HM012', 'option_choice'=>'D'],
            ['room_no' => 'HM013', 'option_choice'=>'D'],
            ['room_no' => 'HM014', 'option_choice'=>'C'],
            ['room_no' => 'HM015', 'option_choice'=>'D'],
            ['room_no' => 'HM016', 'option_choice'=>'D'],
            ['room_no' => 'HM017', 'option_choice'=>'C'],
            ['room_no' => 'HM018', 'option_choice'=>'C'],
            ['room_no' => 'HM019', 'option_choice'=>'C'],
            ['room_no' => 'HM020', 'option_choice'=>'C'],
            ['room_no' => 'HM021', 'option_choice'=>'C'],
            ['room_no' => 'HM022', 'option_choice'=>'C'],
            ['room_no' => 'HM023', 'option_choice'=>'D'],
            ['room_no' => 'HM024', 'option_choice'=>'D'],
            ['room_no' => 'HM025', 'option_choice'=>'C'],
            ['room_no' => 'HM026', 'option_choice'=>'D'],
            ['room_no' => 'HM027', 'option_choice'=>'D'],
            ['room_no' => 'HM028', 'option_choice'=>'C'],
            ['room_no' => 'HM029', 'option_choice'=>'D'],
            ['room_no' => 'HM030', 'option_choice'=>'D'],
            ['room_no' => 'HM031', 'option_choice'=>'C'],
            ['room_no' => 'HM032', 'option_choice'=>'D'],
            ['room_no' => 'HM101', 'option_choice'=>'C'],
            ['room_no' => 'HM102', 'option_choice'=>'C'],
            ['room_no' => 'HM103', 'option_choice'=>'C'],
            ['room_no' => 'HM104', 'option_choice'=>'C'],
            ['room_no' => 'HM105', 'option_choice'=>'D'],
            ['room_no' => 'HM106', 'option_choice'=>'C'],
            ['room_no' => 'HM107', 'option_choice'=>'D'],
            ['room_no' => 'HM108', 'option_choice'=>'C'],
            ['room_no' => 'HM109', 'option_choice'=>'D'],
            ['room_no' => 'HM110', 'option_choice'=>'D'],
            ['room_no' => 'HM111', 'option_choice'=>'C'],
            ['room_no' => 'HM112', 'option_choice'=>'D'],
            ['room_no' => 'HM113', 'option_choice'=>'D'],
            ['room_no' => 'HM114', 'option_choice'=>'C'],
            ['room_no' => 'HM115', 'option_choice'=>'D'],
            ['room_no' => 'HM116', 'option_choice'=>'D'],
            ['room_no' => 'HM117', 'option_choice'=>'C'],
            ['room_no' => 'HM118', 'option_choice'=>'C'],
            ['room_no' => 'HM119', 'option_choice'=>'D'],
            ['room_no' => 'HM120', 'option_choice'=>'C'],
            ['room_no' => 'HM121', 'option_choice'=>'C'],
            ['room_no' => 'HM122', 'option_choice'=>'C'],
            ['room_no' => 'HM123', 'option_choice'=>'C'],
            ['room_no' => 'HM124', 'option_choice'=>'C'],
            ['room_no' => 'HM125', 'option_choice'=>'D'],
            ['room_no' => 'HM126', 'option_choice'=>'C'],
            ['room_no' => 'HM127', 'option_choice'=>'C'],
            ['room_no' => 'HM128', 'option_choice'=>'D'],
            ['room_no' => 'HM129', 'option_choice'=>'D'],
            ['room_no' => 'HM130', 'option_choice'=>'C'],
            ['room_no' => 'HM131', 'option_choice'=>'D'],
            ['room_no' => 'HM132', 'option_choice'=>'D'],
            ['room_no' => 'HM133', 'option_choice'=>'C'],
            ['room_no' => 'HM134', 'option_choice'=>'D'],
            ['room_no' => 'HM135', 'option_choice'=>'D'],
            ['room_no' => 'HM136', 'option_choice'=>'C'],
            ['room_no' => 'HM137', 'option_choice'=>'D'],
            ['room_no' => 'HM138', 'option_choice'=>'C'],
            ['room_no' => 'HM139', 'option_choice'=>'C'],
            ['room_no' => 'HM201', 'option_choice'=>'A'],
            ['room_no' => 'HM202', 'option_choice'=>'A'],
            ['room_no' => 'HM203', 'option_choice'=>'A'],
            ['room_no' => 'HM204', 'option_choice'=>'A'],
            ['room_no' => 'HM205', 'option_choice'=>'B'],
            ['room_no' => 'HM206', 'option_choice'=>'A'],
            ['room_no' => 'HM207', 'option_choice'=>'B'],
            ['room_no' => 'HM208', 'option_choice'=>'A'],
            ['room_no' => 'HM209', 'option_choice'=>'B'],
            ['room_no' => 'HM210', 'option_choice'=>'B'],
            ['room_no' => 'HM211', 'option_choice'=>'A'],
            ['room_no' => 'HM212', 'option_choice'=>'B'],
            ['room_no' => 'HM213', 'option_choice'=>'B'],
            ['room_no' => 'HM214', 'option_choice'=>'A'],
            ['room_no' => 'HM215', 'option_choice'=>'B'],
            ['room_no' => 'HM216', 'option_choice'=>'B'],
            ['room_no' => 'HM217', 'option_choice'=>'A'],
            ['room_no' => 'HM218', 'option_choice'=>'A'],
            ['room_no' => 'HM219', 'option_choice'=>'B'],
            ['room_no' => 'HM220', 'option_choice'=>'A'],
            ['room_no' => 'HM221', 'option_choice'=>'A'],
            ['room_no' => 'HM222', 'option_choice'=>'A'],
            ['room_no' => 'HM223', 'option_choice'=>'A'],
            ['room_no' => 'HM224', 'option_choice'=>'A'],
            ['room_no' => 'HM225', 'option_choice'=>'B'],
            ['room_no' => 'HM226', 'option_choice'=>'A'],
            ['room_no' => 'HM227', 'option_choice'=>'A'],
            ['room_no' => 'HM228', 'option_choice'=>'B'],
            ['room_no' => 'HM229', 'option_choice'=>'B'],
            ['room_no' => 'HM230', 'option_choice'=>'A'],
            ['room_no' => 'HM231', 'option_choice'=>'B'],
            ['room_no' => 'HM232', 'option_choice'=>'B'],
            ['room_no' => 'HM233', 'option_choice'=>'A'],
            ['room_no' => 'HM234', 'option_choice'=>'B'],
            ['room_no' => 'HM235', 'option_choice'=>'B'],
            ['room_no' => 'HM236', 'option_choice'=>'A'],
            ['room_no' => 'HM237', 'option_choice'=>'B'],
            ['room_no' => 'HM238', 'option_choice'=>'A'],
            ['room_no' => 'HM239', 'option_choice'=>'A'],
            ['room_no' => 'HM301', 'option_choice'=>'A'],
            ['room_no' => 'HM302', 'option_choice'=>'A'],
            ['room_no' => 'HM303', 'option_choice'=>'A'],
            ['room_no' => 'HM304', 'option_choice'=>'A'],
            ['room_no' => 'HM305', 'option_choice'=>'B'],
            ['room_no' => 'HM306', 'option_choice'=>'A'],
            ['room_no' => 'HM307', 'option_choice'=>'B'],
            ['room_no' => 'HM308', 'option_choice'=>'A'],
            ['room_no' => 'HM309', 'option_choice'=>'B'],
            ['room_no' => 'HM310', 'option_choice'=>'B'],
            ['room_no' => 'HM311', 'option_choice'=>'A'],
            ['room_no' => 'HM312', 'option_choice'=>'B'],
            ['room_no' => 'HM313', 'option_choice'=>'B'],
            ['room_no' => 'HM314', 'option_choice'=>'A'],
            ['room_no' => 'HM315', 'option_choice'=>'B'],
            ['room_no' => 'HM316', 'option_choice'=>'B'],
            ['room_no' => 'HM317', 'option_choice'=>'A'],
            ['room_no' => 'HM318', 'option_choice'=>'A'],
            ['room_no' => 'HM319', 'option_choice'=>'B'],
            ['room_no' => 'HM320', 'option_choice'=>'A'],
            ['room_no' => 'HM321', 'option_choice'=>'A'],
            ['room_no' => 'HM322', 'option_choice'=>'A'],
            ['room_no' => 'HM323', 'option_choice'=>'A'],
            ['room_no' => 'HM324', 'option_choice'=>'A'],
            ['room_no' => 'HM325', 'option_choice'=>'B'],
            ['room_no' => 'HM326', 'option_choice'=>'A'],
            ['room_no' => 'HM327', 'option_choice'=>'A'],
            ['room_no' => 'HM328', 'option_choice'=>'B'],
            ['room_no' => 'HM329', 'option_choice'=>'B'],
            ['room_no' => 'HM330', 'option_choice'=>'A'],
            ['room_no' => 'HM331', 'option_choice'=>'B'],
            ['room_no' => 'HM332', 'option_choice'=>'B'],
            ['room_no' => 'HM333', 'option_choice'=>'A'],
            ['room_no' => 'HM334', 'option_choice'=>'B'],
            ['room_no' => 'HM335', 'option_choice'=>'B'],
            ['room_no' => 'HM336', 'option_choice'=>'A'],
            ['room_no' => 'HM337', 'option_choice'=>'B'],
            ['room_no' => 'HM338', 'option_choice'=>'A'],
            ['room_no' => 'HM339', 'option_choice'=>'A'],

        ];

        DB::table('room_status')->insert($status);







    }
}
